# Use node 20 as the base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application for production in port 5002
EXPOSE 5002

# Start the application
CMD ["npm", "run", "start"]
